"""
SQLAlchemy models for predictions data
"""
from .gold_layer import (
    MarketMetricsSummary,
    TopMarketsSnapshot,
    CategoryDistribution,
    VolumeTrends,
    HighVolumeActivity,
    PlatformComparison,
    TrendingCategories,
    MarketDetailCache,
    MarketPriceHistory,
    MarketTradeActivity,
    MarketOrderbookDepth,
    RelatedMarkets,
    MarketStatistics,
    MarketSearchCache,
    FilterAggregates,
    WatchlistPopularMarkets,
    RecentlyResolvedMarkets,
    CategoryBreakdownByPlatform,
    VolumeDistributionHistogram,
    MarketLifecycleFunnel,
    TopTradersLeaderboard,
    CategoryPerformanceMetrics,
    PlatformMarketShareTimeseries,
    HourlyActivityHeatmap,
    ResolutionAccuracyTracker,
    # Phase 2: Events models
    EventsSnapshot,
    EventMarkets,
    EventsAggregateMetrics,
)

__all__ = [
    "MarketMetricsSummary",
    "TopMarketsSnapshot",
    "CategoryDistribution",
    "VolumeTrends",
    "HighVolumeActivity",
    "PlatformComparison",
    "TrendingCategories",
    "MarketDetailCache",
    "MarketPriceHistory",
    "MarketTradeActivity",
    "MarketOrderbookDepth",
    "RelatedMarkets",
    "MarketStatistics",
    "MarketSearchCache",
    "FilterAggregates",
    "WatchlistPopularMarkets",
    "RecentlyResolvedMarkets",
    "CategoryBreakdownByPlatform",
    "VolumeDistributionHistogram",
    "MarketLifecycleFunnel",
    "TopTradersLeaderboard",
    "CategoryPerformanceMetrics",
    "PlatformMarketShareTimeseries",
    "HourlyActivityHeatmap",
    "ResolutionAccuracyTracker",
    # Phase 2: Events models
    "EventsSnapshot",
    "EventMarkets",
    "EventsAggregateMetrics",
]
