# =============================================================================
# DigitalOcean App Platform — EventGraph Production Spec
# =============================================================================
#
# Deploy (first time):
#   doctl apps create --spec .do/app.yaml
#
# Update after a push:
#   doctl apps update <APP_ID> --spec .do/app.yaml
#
# Routing (single domain, no CORS issues):
#   /api/*  →  backend  (FastAPI, port 8001)
#   /*      →  frontend (nginx static, port 80)
#
# BEFORE DEPLOYING — replace every value marked 🔑
# =============================================================================

name: eventgraph-denver
region: nyc

# ── Services ──────────────────────────────────────────────────────────────────

services:

  # ── 1. Frontend (nginx static site) ────────────────────────────────────────
  - name: frontend
    github:
      repo: coingraphai/eventgraph-ethdenver-2026
      branch: main
      deploy_on_push: true
    source_dir: frontend           # Docker build context
    dockerfile_path: frontend/Dockerfile  # path from repo root
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xs
    health_check:
      http_path: /health
      initial_delay_seconds: 15
      period_seconds: 30
      timeout_seconds: 5
      failure_threshold: 3
    routes:
      - path: /                    # catch-all — must come AFTER /api route
    envs:
      # Empty string → JS uses relative /api/... paths → DO routes to backend
      - key: VITE_API_URL
        value: ""
        scope: BUILD_TIME
      - key: VITE_API_BASE_URL
        value: ""
        scope: BUILD_TIME

  # ── 2. Backend (FastAPI + gunicorn) ─────────────────────────────────────────
  - name: backend
    github:
      repo: coingraphai/eventgraph-ethdenver-2026
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 8001
    instance_count: 1
    instance_size_slug: professional-xs   # 1 vCPU / 1 GB
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 15
      timeout_seconds: 10
      failure_threshold: 5
    routes:
      - path: /api
    envs:
      - key: ENVIRONMENT
        value: production

      # ── Database ─────────────────────────────────────────────────────────
      - key: POSTGRES_HOST
        value: REPLACE_WITH_DO_DB_HOST       # 🔑
        type: SECRET
      - key: POSTGRES_PORT
        value: "25060"
      - key: POSTGRES_DB
        value: defaultdb
      - key: POSTGRES_USER
        value: doadmin
      - key: POSTGRES_PASSWORD
        value: REPLACE_WITH_DO_DB_PASSWORD   # 🔑
        type: SECRET
      - key: POSTGRES_SSLMODE
        value: require

      - key: DB_POOL_SIZE
        value: "5"
      - key: DB_MAX_OVERFLOW
        value: "10"
      - key: DB_POOL_TIMEOUT
        value: "30"
      - key: DB_POOL_RECYCLE
        value: "1800"

      # ── API Keys ──────────────────────────────────────────────────────────
      - key: DOME_API_KEY
        value: REPLACE_WITH_DOME_API_KEY     # 🔑
        type: SECRET
      - key: ANTHROPIC_API_KEY
        value: REPLACE_WITH_ANTHROPIC_KEY    # 🔑
        type: SECRET

      # ── CORS ─────────────────────────────────────────────────────────────
      # Requests come from same domain via DO's router — CORS not normally hit.
      # Update to your live domain after first deploy.
      - key: CORS_ORIGINS
        value: "http://localhost:5173,http://localhost:3000"

      # ── Gunicorn tuning ───────────────────────────────────────────────────
      - key: WEB_CONCURRENCY
        value: "2"

# ── Workers ───────────────────────────────────────────────────────────────────

workers:

  # ── 3. Data Pipeline Scheduler (5-min delta loads) ─────────────────────────
  - name: pipeline
    github:
      repo: coingraphai/eventgraph-ethdenver-2026
      branch: main
      deploy_on_push: true
    source_dir: data-pipeline
    dockerfile_path: data-pipeline/Dockerfile
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      # ── Database ─────────────────────────────────────────────────────────
      - key: POSTGRES_HOST
        value: REPLACE_WITH_DO_DB_HOST       # 🔑
        type: SECRET
      - key: POSTGRES_PORT
        value: "25060"
      - key: POSTGRES_DB
        value: defaultdb
      - key: POSTGRES_USER
        value: doadmin
      - key: POSTGRES_PASSWORD
        value: REPLACE_WITH_DO_DB_PASSWORD   # 🔑
        type: SECRET
      - key: POSTGRES_SSLMODE
        value: require

      - key: DB_POOL_SIZE
        value: "5"
      - key: DB_POOL_MAX_OVERFLOW
        value: "10"
      - key: DB_BATCH_SIZE
        value: "500"

      # ── Dome API ──────────────────────────────────────────────────────────
      - key: DOME_API_KEY
        value: REPLACE_WITH_DOME_API_KEY     # 🔑
        type: SECRET
      - key: DOME_API_BASE_URL
        value: "https://api.domeapi.com/v1"
      - key: DOME_RATE_LIMIT_RPS
        value: "50"

      # ── Limitless API ─────────────────────────────────────────────────────
      - key: LIMITLESS_API_BASE_URL
        value: "https://api.limitless.exchange"
      - key: LIMITLESS_RATE_LIMIT_RPS
        value: "5"

      # ── Schedule ─────────────────────────────────────────────────────────
      - key: DELTA_SCHEDULE_INTERVAL_MINUTES
        value: "5"
      - key: POLYMARKET_MAX_MARKETS
        value: "500"
      - key: POLYMARKET_MIN_VOLUME_USD
        value: "50000"
      - key: KALSHI_MAX_MARKETS
        value: "500"
      - key: KALSHI_MIN_VOLUME_USD
        value: "10000"
      - key: TRADES_TOP_N_MARKETS
        value: "0"
      - key: KALSHI_TRADES_TOP_N_MARKETS
        value: "0"
      - key: RETRY_MAX_ATTEMPTS
        value: "5"
      - key: API_TIMEOUT_SECONDS
        value: "30"
      - key: MAX_CONCURRENCY
        value: "5"

# ── Jobs ──────────────────────────────────────────────────────────────────────

jobs:

  # ── DB migrations — runs automatically BEFORE every deploy ─────────────────
  - name: db-migrate
    kind: PRE_DEPLOY
    github:
      repo: coingraphai/eventgraph-ethdenver-2026
      branch: main
    source_dir: data-pipeline
    dockerfile_path: data-pipeline/Dockerfile
    run_command: predictions-ingest db migrate
    instance_size_slug: basic-xs
    envs:
      - key: POSTGRES_HOST
        value: REPLACE_WITH_DO_DB_HOST       # 🔑
        type: SECRET
      - key: POSTGRES_PORT
        value: "25060"
      - key: POSTGRES_DB
        value: defaultdb
      - key: POSTGRES_USER
        value: doadmin
      - key: POSTGRES_PASSWORD
        value: REPLACE_WITH_DO_DB_PASSWORD   # 🔑
        type: SECRET
      - key: POSTGRES_SSLMODE
        value: require
