# =============================================================================
# DigitalOcean App Platform — EventGraph Production Spec
# =============================================================================
#
# Deploy:  doctl apps create --spec .do/app.yaml
# Update:  doctl apps update <APP_ID> --spec .do/app.yaml
#
# Routing (single domain, no CORS):
#   /api/*  →  backend  (FastAPI, port 8001)
#   /*      →  frontend (nginx static, port 80)
#
# BEFORE FIRST DEPLOY — fill in every placeholder marked 🔑
# =============================================================================

name: eventgraph
region: nyc

# ── Services ──────────────────────────────────────────────────────────────────

services:

  # ── 1. Frontend (nginx static site) ────────────────────────────────────────
  - name: frontend
    source_dir: frontend
    dockerfile_path: Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xs          # 1 vCPU / 512 MB — fine for static
    health_check:
      http_path: /health
      initial_delay_seconds: 15
      period_seconds: 30
      timeout_seconds: 5
      failure_threshold: 3
    routes:
      - path: /                           # catch-all — must be LAST in DO routing
    envs:
      # VITE_API_URL="" means the JS code uses relative paths like /api/...
      # DO's router sends /api/* to the backend service — zero CORS needed.
      - key: VITE_API_URL
        value: ""
        scope: BUILD_TIME
      - key: VITE_API_BASE_URL
        value: ""
        scope: BUILD_TIME

  # ── 2. Backend (FastAPI) ────────────────────────────────────────────────────
  - name: backend
    source_dir: backend
    dockerfile_path: Dockerfile
    http_port: 8001
    instance_count: 1
    instance_size_slug: professional-xs   # 1 vCPU / 1 GB — needed for ML + DB pool
    health_check:
      http_path: /health
      initial_delay_seconds: 60           # DB + cache warm-up takes time
      period_seconds: 15
      timeout_seconds: 10
      failure_threshold: 5
    routes:
      - path: /api                        # backend owns /api/*
      - path: /health                     # expose health for external monitoring
    envs:
      - key: ENVIRONMENT
        value: production

      # ── Database ─────────────────────────────────────────────────────────
      - key: POSTGRES_HOST
        value: REPLACE_WITH_DO_DB_HOST    # 🔑 e.g. db-xxx.db.ondigitalocean.com
        type: SECRET
      - key: POSTGRES_PORT
        value: "25060"
      - key: POSTGRES_DB
        value: defaultdb
      - key: POSTGRES_USER
        value: doadmin
      - key: POSTGRES_PASSWORD
        value: REPLACE_WITH_DO_DB_PASSWORD  # 🔑
        type: SECRET
      - key: POSTGRES_SSLMODE
        value: require

      # Connection pool — keep low for shared managed DB
      - key: DB_POOL_SIZE
        value: "5"
      - key: DB_MAX_OVERFLOW
        value: "10"
      - key: DB_POOL_TIMEOUT
        value: "30"
      - key: DB_POOL_RECYCLE
        value: "1800"

      # ── API Keys ──────────────────────────────────────────────────────────
      - key: DOME_API_KEY
        value: REPLACE_WITH_DOME_API_KEY    # 🔑
        type: SECRET
      - key: ANTHROPIC_API_KEY
        value: REPLACE_WITH_ANTHROPIC_KEY   # 🔑
        type: SECRET

      # ── CORS ─────────────────────────────────────────────────────────────
      # In production, requests arrive via DO's load balancer (same domain).
      # CORS only matters for direct API access (devtools, staging, etc.).
      # Set to your custom domain once configured, or keep localhost for now.
      - key: CORS_ORIGINS
        value: "http://localhost:5173,http://localhost:3000"

# ── Workers ───────────────────────────────────────────────────────────────────

workers:

  # ── 3. Data Pipeline Scheduler (5-min delta loads) ─────────────────────────
  - name: pipeline
    source_dir: data-pipeline
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xs          # 1 vCPU / 512 MB — pipeline is I/O bound
    envs:
      # ── Database ─────────────────────────────────────────────────────────
      - key: POSTGRES_HOST
        value: REPLACE_WITH_DO_DB_HOST    # 🔑 same as backend
        type: SECRET
      - key: POSTGRES_PORT
        value: "25060"
      - key: POSTGRES_DB
        value: defaultdb
      - key: POSTGRES_USER
        value: doadmin
      - key: POSTGRES_PASSWORD
        value: REPLACE_WITH_DO_DB_PASSWORD  # 🔑
        type: SECRET
      - key: POSTGRES_SSLMODE
        value: require

      # DB pool — pipeline does batch writes, keep moderate
      - key: DB_POOL_SIZE
        value: "5"
      - key: DB_POOL_MAX_OVERFLOW
        value: "10"
      - key: DB_BATCH_SIZE
        value: "500"

      # ── Dome API ──────────────────────────────────────────────────────────
      - key: DOME_API_KEY
        value: REPLACE_WITH_DOME_API_KEY  # 🔑
        type: SECRET
      - key: DOME_API_BASE_URL
        value: "https://api.domeapi.com/v1"
      - key: DOME_RATE_LIMIT_RPS
        value: "50"

      # ── Limitless API ──────────────────────────────────────────────────────
      - key: LIMITLESS_API_BASE_URL
        value: "https://api.limitless.exchange"
      - key: LIMITLESS_RATE_LIMIT_RPS
        value: "5"

      # ── Schedule (5-min delta, no trades) ────────────────────────────────
      - key: DELTA_SCHEDULE_INTERVAL_MINUTES
        value: "5"
      - key: POLYMARKET_MAX_MARKETS
        value: "500"
      - key: POLYMARKET_MIN_VOLUME_USD
        value: "50000"
      - key: KALSHI_MAX_MARKETS
        value: "500"
      - key: KALSHI_MIN_VOLUME_USD
        value: "10000"
      - key: TRADES_TOP_N_MARKETS
        value: "0"                        # disable trades — saves 324K API calls/month
      - key: KALSHI_TRADES_TOP_N_MARKETS
        value: "0"

      # ── Retry / reliability ──────────────────────────────────────────────
      - key: RETRY_MAX_ATTEMPTS
        value: "5"
      - key: API_TIMEOUT_SECONDS
        value: "30"
      - key: MAX_CONCURRENCY
        value: "5"

# ── Jobs ──────────────────────────────────────────────────────────────────────

jobs:

  # ── DB migrations — runs automatically BEFORE every deploy ─────────────────
  # Applies all SQL migrations in data-pipeline/migrations/
  - name: db-migrate
    kind: PRE_DEPLOY
    source_dir: data-pipeline
    dockerfile_path: Dockerfile
    run_command: predictions-ingest db migrate
    instance_size_slug: basic-xs
    envs:
      - key: POSTGRES_HOST
        value: REPLACE_WITH_DO_DB_HOST    # 🔑
        type: SECRET
      - key: POSTGRES_PORT
        value: "25060"
      - key: POSTGRES_DB
        value: defaultdb
      - key: POSTGRES_USER
        value: doadmin
      - key: POSTGRES_PASSWORD
        value: REPLACE_WITH_DO_DB_PASSWORD  # 🔑
        type: SECRET
      - key: POSTGRES_SSLMODE
        value: require
